$( function() {
			var availableTags = [
		'Afghanistan', 
		'Albanie' , 
		'Algerie' , 
		'Andorre' , 
		'Angola' , 
		'Antigua-et-Barbuda' , 
		'Argentine' , 
		'Armenie' , 
		'Australie' , 
		'Autriche' , 
		'Azerbaidjan' , 
		'Bahamas' , 
		'Bahrein' , 
		'Bangladesh' , 
		'Barbade' , 
		'Belarus' , 
		'Belgique' , 
		'Belize' , 
		'Benin' , 
		'Bermudes' , 
		'Bhoutan' , 
		'Bolivie' , 
		'Bosnie-Herzegovine' , 
		'Botswana' , 
		'Bresil' , 
		'Brunei Darussalam' , 
		'Bulgarie' , 
		'Burkina Faso' , 
		'Burundi' , 
		'Cap-Vert' , 
		'Cambodge' , 
		'Cameroun' , 
		'Canada' , 
		'Republique centrafricaine' , 
		'Tchad' , 
		'Chili' , 
		'Chine' , 
		'Colombie' , 
		'Comores' , 
		'Congo' , 
		'Costa Rica' , 
		'Cote d\'Ivoire' , 
		'Croatie' , 
		'Cuba' , 
		'Chypre' , 
		'Tchequie' , 
		'Republique democratique du Congo' , 
		'Danemark' , 
		'Djibouti' , 
		'Dominique' , 
		'Republique dominicaine' , 
		'Equateur' , 
		'Egypte' , 
		'Guinee equatoriale' , 
		'Erythree' , 
		'Estonie' , 
		'Eswatini' , 
		'Ethiopie' , 
		'Feroe' , 
		'Fidji' , 
		'Finlande' , 
		'France' , 
		'Gabon' , 
		'Gambie' , 
		'Georgie' , 
		'Allemagne' , 
		'Ghana' , 
		'Gibraltar' , 
		'Grece' , 
		'Groenland' , 
		'Grenade' , 
		'Guatemala' , 
		'Guernesey' , 
		'Guinee' , 
		'Guinee-Bissau' , 
		'Guyana' , 
		'Haiti' , 
		'Vatican' , 
		'Honduras' , 
		'Hong Kong' , 
		'Hongrie' , 
		'Islande' , 
		'Inde' , 
		'Indonesie' , 
		'Iran' , 
		'Iraq' , 
		'Irlande' , 
		'Israel' , 
		'Italie' , 
		'Jamaique' , 
		'Japon' , 
		'Jordanie' , 
		'Kazakhstan' , 
		'Kenya' , 
		'Kiribati' , 
		'Koweit' , 
		'Kirghizistan' , 
		'Laos' , 
		'Lettonie' , 
		'Liban' , 
		'Lesotho' , 
		'Liberia' , 
		'Libye' , 
		'Liechtenstein' , 
		'Lituanie' , 
		'Luxembourg' , 
		'Macao' , 
		'Madagascar' , 
		'Malawi' , 
		'Malaisie' , 
		'Maldives' , 
		'Mali' , 
		'Malte' , 
		'Mauritanie' , 
		'Maurice' , 
		'Mexique' , 
		'Micronesie' , 
		'Moldavie' , 
		'Monaco' , 
		'Mongolie' , 
		'Montenegro' , 
		'Maroc' , 
		'Mozambique' , 
		'Myanmar' , 
		'Namibie' , 
		'Nauru' , 
		'Nepal' , 
		'Pays-Bas' , 
		'Nouvelle-Zelande' , 
		'Nicaragua' , 
		'Niger' , 
		'Nigeria' , 
		'Niue' , 
		'Coree du Nord' , 
		'Macedoine du Nord' , 
		'Norvege' , 
		'Oman' , 
		'Pakistan' , 
		'Palaos' , 
		'Palestine' , 
		'Panama' , 
		'Papouasie-Nouvelle-Guinee' , 
		'Paraguay' , 
		'Perou' , 
		'Philippines' , 
		'Pologne' , 
		'Portugal' , 
		'Qatar' , 
		'Roumanie' , 
		'Russie' , 
		'Rwanda' , 
		'Saint-Kitts-et-Nevis' , 
		'Sainte-Lucie' , 
		'Saint-Vincent-et-lesGrenadines' , 
		'Salvador' , 
		'Samoa' , 
		'Saint-Marin' , 
		'Sao Tome-et-Principe' , 
		'Arabie saoudite' , 
		'Senegal' , 
		'Serbie' , 
		'Seychelles' , 
		'Sierra Leone' , 
		'Singapour' , 
		'Slovaquie' , 
		'Slovenie' , 
		'Iles Salomon' , 
		'Somalie' , 
		'Afrique du Sud' , 
		'Coree du Sud' , 
		'Soudan du Sud' , 
		'Espagne' , 
		'Sri Lanka' , 
		'Soudan' , 
		'Suriname' , 
		'Suede' , 
		'Suisse' , 
		'Syrie' , 
		'Taiwan' , 
		'Tadjikistan' , 
		'Tanzanie' , 
		'Thailande' , 
		'Timor-Leste' , 
		'Togo' , 
		'Tonga' , 
		'Trinite-et-Tobago' , 
		'Tunisie' , 
		'Turquie' , 
		'Turkmenistan' , 
		'Tuvalu' , 
		'Ouganda' , 
		'Ukraine' , 
		'Emirats arabes unis' , 
		'Royaume-Uni' , 
		'Etats-Unis' , 
		'Uruguay' , 
		'Ouzbekistan' , 
		'Vanuatu' , 
		'Venezuela' , 
		'Viet Nam' , 
		'Yemen' , 
		'Zambie' , 
		'Zimbabwe' 
			];
			$( ".Champs" ).autocomplete({
			  source: availableTags
			});
		  } );